Forum/Forum/Areas/Admin/Controllers/CategoryController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.DataAccess;
using Forum.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Forum.DataAccess.Repository;

namespace Forum.Areas.Forum.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Moderator)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _uniofWork;

        public CategoryController(IUnitOfWork uniofWork)
        {
            _uniofWork = uniofWork;
        }

        // GET: Forum/Category
        public async Task<IActionResult> Index()
        {
            return View(await _uniofWork.Category.GetListAsync());
        }

        // GET: Forum/Category/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var category = await _uniofWork.Category.GetByIdAsync(id);
            if (category == null)
                return NotFound();
            return View(category);
        }

        // GET: Forum/Category/Create
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Category());
            else
                return View(await _uniofWork.Category.GetByIdAsync(id));
        }

        // POST: Forum/Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("Title,Id")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)
                    await _uniofWork.Category.CreateAsync(category);
                else
                    _uniofWork.Category.UpdateAsync(category);
                await _uniofWork.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _uniofWork.Category.GetByIdAsync(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            await _uniofWork.Category.DeleteJsAsync(id);
            return Json(new { success = true, message = "Delete Successful" });
        }
    }
}

Forum/Forum/Areas/Admin/Controllers/PostController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Forum.Models;
using Forum.DataAccess.Repository.IRepository;
using Forum.DataAccess.Data;
using System;
using System.Security.Claims;
using Forum.DataAccess.Specification;
using Forum.Models.ViewModels;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Forum.DataAccess.Services;
using Forum.DataAccess;
using Forum.DataAccess.Repository;

namespace Forum.Areas.Forum.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly IUnitOfWork _uniofWork;
        private readonly ApplicationDbContext _db;                  
        private readonly IFileManager _fileManager;     // for upload images on server

        public PostController(IFileManager fileManager,
            ApplicationDbContext db,
            IUnitOfWork uniofWork)
        {
            _fileManager = fileManager;
            _db = db;
            _uniofWork = uniofWork;
        }

        // GET: Admin/Post
        public async Task<IActionResult> Index()
        {
            return View(await _uniofWork.Post.GetListAsync());
        }

        // GET: Admin/Post/Details/5
        public async Task<IActionResult> Details(int id)
        {
            // using Specification
            var spec = new PostWithSpecification(id);
            var post = await _uniofWork.Post.GetByIdAsyncWithSpec(spec);
            if (post == null)
                return NotFound();
            return View(post);
        }

        // GET: Admin/Post/Create
        [Authorize()]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            //var ids = GetUserInfo();
            PostVM postVM = new PostVM()
            {
                Post = new Post(),
                CategoryList = _uniofWork.Category.GetSelectListAsync()
            };

            if (id == 0)
                return View(postVM);
            else
                postVM.Post = await _uniofWork.Post.GetByIdAsync(id);

                // access to edit have admin, moderator and post author
                bool result = AccessRights.AuthorAdminAccessRight(HttpContext, postVM.Post.ApplicationUserId, _db);
                if (result)
                    return View(postVM);
                return new RedirectResult("~/Identity/Account/AccessDenied");
        }

        // POST: Admin/Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(PostVM postVM)
        {
            if (ModelState.IsValid)
            {
                // SAVE IMAGE
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    // DELETE OLD IMAGE
                    if (postVM.Post.Id != 0)
                    {
                        Post obj = await _uniofWork.Post.GetByIdAsync(postVM.Post.Id);
                        _fileManager.RemoveImage(obj.ImageUrl);
                    }
                    postVM.Post.ImageUrl = await _fileManager.SaveImage(files, SD.Post_Image_Base_Path, SD.Post_Image_Result_Path);
                }
                else
                {
                    // update when they do not change the image
                    if (postVM.Post.Id != 0)
                    {
                        Post objFromDb = await _uniofWork.Post.GetByIdAsync(postVM.Post.Id);
                        postVM.Post.ImageUrl = objFromDb.ImageUrl;
                    }
                }

                if (postVM.Post.Id == 0)
                {
                    // get logged user
                    var claimsIdentity = (ClaimsIdentity)User.Identity;
                    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                    postVM.Post.ApplicationUserId = claim.Value;
                    await _uniofWork.Post.CreateAsync(postVM.Post);
                }
                else
                {
                    _uniofWork.Post.UpdateAsync(postVM.Post);
                }
                await _uniofWork.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postVM.Post);
        }

        // GET: Admin/Post/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var post = await _uniofWork.Post.GetByIdAsync(id);
            if (post == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
             
            // delete images and comments -> post
            _fileManager.RemoveImage(post.ImageUrl);
            _uniofWork.Post.DeleteAllCommentByPostId(id);
            await _uniofWork.Post.DeleteJsAsync(id);
            return Json(new { success = true, message = "Delete Successful" });
        }

        // get API for admin
        [HttpGet]
        public IActionResult GetPostForAdmin()
        {
            var objList = _db.Posts.ToList();
            foreach(var item in objList)
            {
                item.Category = _db.Categories.Find(item.CategoryId);
                item.ApplicationUser = _db.ApplicationUsers.Find(item.ApplicationUserId);
            }
            return Json(new { data = objList });
        }
    }
}

Forum/Forum/Areas/Admin/Controllers/UserController.cs
using Forum.DataAccess;
using Forum.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Forum.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Moderator)]
    public class UserController : Controller
    {

        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        // API calls will be here
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

            return Json(new { data = userList });
        }


        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while locking / unlocking" });
            }
            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                // user is currectle locked, need to unlock it now
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Operation Successful." });
        }
    }
}

Forum/Forum/Views/Shared/_Layout.cshtml
@using Forum.DataAccess
@using Forum.DataAccess.Data
@inject ApplicationDbContext db


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    @RenderSection("ExtraCss", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-toggleable-xl navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Forum" asp-controller="Home" asp-action="Index">Forum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-xl-inline-flex flex-xl-row-reverse">
                    <partial name="_LoginPartial" />

                    <a class="btn btn-primary" asp-area="Forum" asp-controller="Home" asp-action="AddOrEdit">Add Question</a>

                    <form class="form-inline my-2 mr-5 my-lg-0" method="get"
                          asp-area="Forum" asp-controller="Home" asp-action="Index">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                    </form>

                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Moderator))
                        {
                            <li class="nav-item dropdown show">
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Post" asp-action="Index">Post</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }


                        <li class="nav-item dropdown show">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Category
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                @foreach (var item in db.Categories.ToList())
                                {
                                    <a class="dropdown-item"
                                       asp-area="" asp-controller="Home" asp-action="Index"
                                       asp-route-categoryId="@item.Id"
                                       onclick="generateNewUrl(event, 'category', @item.Id);">@item.Title</a>
                                }
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Forum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/filter.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://kit.fontawesome.com/06b132df8c.js" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>